[workspace]
authors = ["Ina <ina.gege@web.de>"]
channels = ["conda-forge"]
name = "Codebase_MasterThesis"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

# CONDA_OVERRIDE_CUDA="12.0" pixi install

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
python = ">=3.9.1,<3.15"
accelerate = "*"
ffmpeg = "*"
ninja = "*"
packaging = "*"
torchvision = "*"
torchaudio = "*"
cuda-version = "12.9.*"
pip = ">=25.3,<26"
pandas = "*"
numpy = "*"
pytest = ">=9.0.2,<10"
scikit-learn = ">=1.8.0,<2"
seaborn = ">=0.13.2,<0.14"

[target.linux-64]
[target.linux-64.dependencies]
pytorch-gpu = "*"

[target.linux-64.pypi-dependencies]
qwen-omni-utils = {version = "*", extras=["decord"]}
transformers = { git = "https://github.com/huggingface/transformers", tag = "v4.51.3-Qwen2.5-Omni-preview"}
soundfile = "*"

[target.osx-64]
[target.osx-64.dependencies]
pixi-kernel = "*"
ipykernel = "*"
pixi-pycharm = "*"
matplotlib = "*"
jupyterlab = "*"

[activation]
env = { PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True" }
