[workspace]
authors = ["Ina <ina.gege@web.de>"]
channels = ["conda-forge"]
name = "Codebase_MasterThesis"
platforms = ["linux-64"]
version = "0.1.0"

# CONDA_OVERRIDE_CUDA="12.0" pixi install

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
python = ">=3.9.1,<3.15"
accelerate = "*"
ffmpeg = "*"
ninja = "*"
packaging = "*"
pytorch-gpu = "*"
torchvision = "*"
torchaudio = "*"
cuda-version = "12.9.*"
pip = "*"
pandas = "*"
numpy = "*"

[activation]
env = { PYTORCH_CUDA_ALLOC_CONF = "expandable_segments:True" }

[pypi-dependencies]
qwen-omni-utils = {version = "*", extras=["decord"]}
transformers = { git = "https://github.com/huggingface/transformers", tag = "v4.51.3-Qwen2.5-Omni-preview"}
soundfile = "*"      
